#! /bin/sh
#
# Created by NJG on Thu May  9 11:43:50  2002
# Updated by NJG on Tuesday, May 24, 2016

export OS=`uname -s`
# if OSX use "stat cmd
# if Linux us date with -r option

export STATCMD="stat -f%Sm"

case $OS in 
    Linux) STATCMD="date -r" 
esac 

if [ -f lib/PDQ_Lib.h ]; then
  # static char *version = "Version 7.0.0 Build 052116";
  # awk ' /VERSION/ {sub(/^\"/, "", $5); sub(/\";/, "", $8); print "PDQ " $5 " " $6 " " $7 " " $8} ' lib/PDQ_Lib.h
  # Changed to #define constant for PDQ 7.0.0
  # #define VERSION    "Version 7.0.0 Build 052116"
  awk ' /PDQ_VERSION/ {sub(/^\"/, "", $3); sub(/\"/, "", $6); print "PDQ " $3 " " $4 " " $5 " " $6} ' lib/PDQ_Lib.h
fi

if [ -f lib/libpdq* ]; then
  COMPILETIME=`$STATCMD lib/libpdq*`
  printf "Compiled on %s\n" "$COMPILETIME"
fi

exit 0
