#! /bin/sh
#
# Created by NJG on Thu May  9 11:43:50  2002
#
#  $Id$
#

export OS=`uname -s`

#On OSX use "stat cmd
#On Linux us date with -r option

export STATCMD="stat -f%Sm"

case $OS in 
    Linux) STATCMD="date -r" 
esac 

if [ -f lib/PDQ_Lib.h ]; then
  awk ' /static char \*version/ {sub(/^\"/, "", $5); sub(/\";/, "", $8); print "PDQ " $5 " " $6 " " $7 " " $8} ' lib/PDQ_Lib.h
fi

if [ -f lib/libpdq* ]; then
  COMPILETIME=`$STATCMD lib/libpdq*`
  printf "Compiled on %s\n" "$COMPILETIME"
fi

exit 0
