#! /bin/sh
#
# Clean and remake all the PDQ files in each chapter subdirectory.
#
# Created by NJG: Fri Aug 24 16:39:23  2001
#
#  $Id$
#
#---------------------------------------------------------------------

(cd lib; make)
(cd perl5; ./setup.sh)
(cd python; make)
(cd R; cp ../lib/*.[ch] pdq/src; R CMD INSTALL pdq)

#---------------------------------------------------------------------

for num in 2 3 6 7 8 9 ; do
	echo; echo
	echo "Making chapter $num PDQ files ..."
	(cd examples/ppa_1998/chap$num; make -f Makefile all)
done

#---------------------------------------------------------------------

exit 0

#---------------------------------------------------------------------
