#
#  $Id$
#
#---------------------------------------------------------------------

ALL    = \
	Ch2_Closed.java \
	Ch2_Open.java \
	Ch3_Closed.java \
	Ch3_FESC.java \
	Ch3_Feedback.java \
	Ch3_MCTest.java \
	Ch3_MultiClass.java \
	Ch3_Passport.java \
	Ch3_ShadowCPU.java \
	Ch3_SimpleSeries.java \
	Ch6_DBC.java \
	Ch7_Multibus.java \
	Ch7_abcache.java \
	Ch8_Baseline.java \
	Ch8_Scaleup.java \
	Ch8_Upgrade1.java \
	Ch8_Upgrade2.java \
	Ch9_HTTP.java \
	Ch9_IIS.java \
	Ch9_eBiz.java \

#---------------------------------------------------------------------

compile:
	compile_all.sh

test:
	test.sh

#---------------------------------------------------------------------

clean:
	-/bin/rm -rf classes *.class diff.log *.tst

#---------------------------------------------------------------------

