# This file was automatically generated by SWIG
package pdq;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package pdq;
bootstrap pdq;
package pdq;
@EXPORT = qw( );
1;
