#
#  $Id$
#
#---------------------------------------------------------------------

all:
	-(cd chap2; make)
	-(cd chap3; make)
	-(cd chap6; make)
	-(cd chap8; make)
	-(cd chap9; make)

#---------------------------------------------------------------------

test:
	-(cd chap2; make test)
	-(cd chap3; make test)
	-(cd chap6; make test)
	-(cd chap8; make test)
	-(cd chap9; make test)

#---------------------------------------------------------------------


clean:
	-(cd chap2; make clean)
	-(cd chap3; make clean)
	-(cd chap6; make clean)
	-(cd chap7; make clean)
	-(cd chap8; make clean)
	-(cd chap9; make clean)

#---------------------------------------------------------------------

