#!/bin/sh
# $Id$
#grep version lib/PDQ_Lib.h | sed -n 's/^.*static char \*version.*=.*\([0-9][0-9]*[.][0-9][0-9]*[.][0-9][0-9]*\) .*$/\1/p'
grep VERSION /PDQ_Lib.h | sed -n 's/.*VERSION.*\([0-9][0-9]*[.][0-9][0-9]*[.][0-9][0-9]*\) .*$/\1/p'
